# Generated by Django 5.2.8 on 2026-02-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='code',
            field=models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('info', 'Info')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_push_notif',
            field=models.BooleanField(default=False),
        ),
    ]
