# Generated by Django 5.2.8 on 2026-02-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_notification_code_notification_is_push_notif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_push_notif',
        ),
    ]
