# Generated by Django 5.2.8 on 2026-02-03 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0003_remove_notification_is_push_notif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-sent_at']},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='realtime_no_recipie_594ab8_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'sent_at'], name='realtime_no_recipie_43c032_idx'),
        ),
    ]
