"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
from datetime import timedelta

# Initialize environment object
env = environ.Env()


# Core settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read the .env file
environ.Env.read_env(str(BASE_DIR / ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG")

if DEBUG:
    ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
else:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cloudinary",
    "cloudinary_storage",
    "axes",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "django_extensions",
    "corsheaders",
    # APPS
    "users",
    "api",
    "realtime",
    "website",
]

ASGI_APPLICATION = "core.asgi.application"


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # corsheaders
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "axes.middleware.AxesMiddleware",  # Axes middleware
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG:

    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(default=env("DATABASE_URL")),
    }
else:

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "postgres",
            "USER": "postgres",
            "PASSWORD": "postgres",
            "HOST": "postgres",
            "PORT": 5432,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ======== CUSTOM SETTINGS ======== #

# Media with cloudinary
IS_CLOUDINARY = env.bool("IS_CLOUDINARY")
if IS_CLOUDINARY:
    SECURE_CONTENT_SECURITY_POLICY = "default-src 'self' https://res.cloudinary.com;"
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": env("CLOUD_NAME"),
        "API_KEY": env("API_KEY"),
        "API_SECRET": env("API_SECRET"),
    }
    CLOUDINARY_STORAGE_DEFAULT_TYPE = "authenticated"
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"


# Redis
if DEBUG:
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [("127.0.0.1", 6379)],
            },
        },
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": env("REDIS_URL", default="redis://127.0.0.1:6379/1"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }

# Session caching (optional)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# Email
EMAIL_BACKEND = env("EMAIL_BACKEND")
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env.int("EMAIL_PORT")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL = env("DEFAULT_FROM_EMAIL")
DEFAULT_FROM_EMAIL = env("EMAIL_HOST_USER")


# AXES
AXES_FAILURE_LIMIT = 5

# Lock out duration (1 hour)
AXES_COOLOFF_TIME = 60 * 60

# Track login attempts by username + IP
# Default is by username+IP, no deprecated settings used

# Lock out at failure
AXES_LOCK_OUT_AT_FAILURE = True

# Optional: ignore local/dev IPs so you don't lock yourself out
AXES_IGNORE_IP_ADDRESSES = ["127.0.0.1", "::1"]

# Log failed attempts (optional)
AXES_LOCKOUT_CALLABLE = None  # default logs attempts

# =========== Security Best Practices =============

# HTTPS only cookies
CSRF_COOKIE_SECURE = True
CSRF_FAILURE_VIEW = "utils.csrf.csrf_failure_view"
CSRF_TRUSTED_ORIGINS = [
    "https://localhost:5173",
    "https://127.0.0.1:5173",
]


SESSION_COOKIE_SECURE = True

# HSTS headers (forces HTTPS)
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Force HTTPS redirects
SECURE_SSL_REDIRECT = True

# Prevent content sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# XSS protection
SECURE_BROWSER_XSS_FILTER = True

# Frame options
X_FRAME_OPTIONS = "DENY"
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesBackend",  # must be first
    # "django.contrib.auth.backends.ModelBackend",
    "users.backends.EmailBackend",
]


# RESTAPI
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # simplejwt authentication class
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "20/min",
        "user": "100/min",
    },
}


# SIMPLE JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=5),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # Cookie mode
    "AUTH_COOKIE": "access_token",
    "AUTH_COOKIE_SECURE": True,  # HTTPS only
    "AUTH_COOKIE_HTTP_ONLY": True,  # JS cannot access it
    "AUTH_COOKIE_SAMESITE": "None",  # Required for cross-origin React
    "AUTH_COOKIE_PATH": "/",  # Global cookie
    "AUTH_COOKIE_DOMAIN": None,  # Set domain in production
    "AUTH_COOKIE_REFRESH": "refresh_token",
    "AUTH_COOKIE_REFRESH_SECURE": True,
    "AUTH_COOKIE_REFRESH_HTTP_ONLY": True,
    "AUTH_COOKIE_REFRESH_SAMESITE": "None",
    "AUTH_COOKIE_REFRESH_PATH": "/",
}

# Custom User model
AUTH_USER_MODEL = "users.User"

# Two fa setting
IS_TWOFA_MANDATORY = env.bool("IS_TWOFA_MANDATORY")

# Cors Headers
CORS_ALLOWED_ORIGINS = [
    "https://localhost:5173",
    "https://localhost:8000",
    "https://127.0.0.1:8000",
]


# Optional: allow credentials like cookies
CORS_ALLOW_CREDENTIALS = True

# Optional: allow all headers and methods
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-csrftoken",
    "accept",
    "origin",
    "user-agent",
    "accept-encoding",
    "connection",
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]
