# Generated by Django 5.2.8 on 2025-12-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='none', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='framework',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='framework',
            unique_together={('language', 'name')},
        ),
    ]
