# Generated by Django 5.2.8 on 2026-02-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='allow_proifle_pic_change',
            field=models.BooleanField(default=False),
        ),
    ]
