# Generated by Django 5.2.8 on 2026-02-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_setting_allow_proifle_pic_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='allow_proifle_pic_change',
            new_name='allow_profile_pic_change',
        ),
    ]
