# Generated by Django 5.2.8 on 2025-12-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtask',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
