# Generated by Django 5.2.8 on 2025-12-27 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_task', '0002_learningtask_is_rated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taskreview',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_review_per_user_per_task'),
        ),
    ]
