# Generated by Django 5.2.8 on 2026-01-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_task', '0004_learningtasklimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtask',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('rated', 'Rated')], default='draft', max_length=20),
        ),
    ]
