# Generated by Django 5.2.8 on 2026-01-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_task', '0005_learningtask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtask',
            name='is_rated',
        ),
    ]
