# Generated by Django 5.2.8 on 2026-02-03 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_task', '0008_alter_learningtask_user_alter_taskreview_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningtasklimit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_limit', to=settings.AUTH_USER_MODEL),
        ),
    ]
