# Generated by Django 5.2.8 on 2026-02-05 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_task', '0010_taskbonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbonus',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
