# Generated by Django 5.2.8 on 2026-02-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_task', '0011_alter_taskbonus_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbonus',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='learning_task.learningtask'),
        ),
    ]
