# Generated by Django 5.2.8 on 2026-02-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_task', '0012_alter_taskbonus_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbonus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
