# Generated by Django 5.2.8 on 2025-11-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
