# Generated by Django 5.2.8 on 2026-01-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_changepasswordviaemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='twofa_endabled',
            new_name='twofa_enabled',
        ),
    ]
