# Generated by Django 5.2.8 on 2026-02-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_twofa_endabled_user_twofa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notif_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notif_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
