# Generated by Django 5.2.8 on 2026-02-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_notif_enabled_user_push_notif_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='field',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('ai', 'AI'), ('embedded', 'Embedded'), ('cyber', 'Cyber'), ('other', 'Other')], default='frontend', max_length=50),
        ),
    ]
