# Generated by Django 5.2.8 on 2026-08-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
